name: Build Project

on:
  pull_request:
    branches:
      - master
      - develop
      - feature/**
  push:
    branches:
      - master
      - develop
      - feature/**
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build-cmake-posix:
    name: cmake
    continue-on-error: false

    strategy:
      matrix:
        os: [ubuntu-22.04]
        cxx: [g++, clang++]
        standalone: [OFF, ON]
        header-only: [OFF, ON]

        # macOS builds are kind of slow, so let's just do one configuration
        include:
          - os: macos-13
            cxx: clang++
            standalone: OFF
            header-only: OFF

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Get vanilla Asio
        run: |
          mkdir -p asio
          wget -O - https://github.com/chriskohlhoff/asio/archive/refs/tags/asio-1-24-0.tar.gz | tar --strip-components=2 -xz -C asio

      - name: Cache Boost
        uses: actions/cache@v4
        with:
          path: '${{ github.workspace }}/build-downloads/boost/*'
          key: 'boost-1.81.0'

      - name: CMake
        env:
          CXX: ${{ matrix.cxx }}
        run: |
          cmake -B ${{ github.workspace }}/build -DASIOEXT_ASIO_ROOT=../asio -DASIOEXT_STANDALONE=${{ matrix.standalone }} -DASIOEXT_HEADER_ONLY=${{ matrix.header-only }}

      - name: Build
        run: |
          cmake --build ${{ github.workspace }}/build

      - name: Run tests
        working-directory: ${{ github.workspace }}/build
        run: |
          ctest
